language: ruby
env:
  - RAILS_ENV=test
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - bundle exec rails db:create db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rake
cache:
  - bundler: true
